import os
import json
import litellm
import re
from datetime import date
from dotenv import load_dotenv

# Load environment variables (e.g., from ../../.env)
load_dotenv(dotenv_path=os.path.join(os.path.dirname(__file__), "..", "..", ".env"))

SYSTEM_PROMPT = """
You are a Budget Planning Agent.

Rules:
- Create realistic, structured budgets
- Align allocations with goals
- Highlight trade-offs
- Do NOT give financial advice

Return ONLY valid JSON with this schema:

{
  "budget_summary": "Overall summary of the budget",
  "allocations": [
    {
      "category": "Category name",
      "amount": "$Amount",
      "percentage": "Percentage of total income",
      "notes": "Optional notes"
    }
  ],
  "remaining_balance": "$Remaining amount",
  "goal_alignment_notes": [
    "Note on how this aligns with the user's goals"
  ]
}
"""

def read_input(path="budget_input.txt"):
    try:
        with open(path, "r", encoding="utf-8") as f:
            return f.read()
    except FileNotFoundError:
        print(f"Error: {path} not found.")
        return None

def extract_json(response_content):
    """Attempts to robustly parse JSON out of an LLM response."""
    try:
        return json.loads(response_content)
    except json.JSONDecodeError:
        # Try stripping markdown blocks
        match = re.search(r"```(?:json)?\s*([\s\S]*?)```", str(response_content))
        if match:
            try:
                return json.loads(match.group(1).strip())
            except:
                pass
        
        # Try finding anything between braces
        match = re.search(r"\{[\s\S]*\}", str(response_content))
        if match:
            try:
                return json.loads(match.group(0).strip())
            except:
                pass
    raise ValueError("Failed to extract valid JSON from the model's response.")

def generate_budget(text, model_name="gpt-4o-mini"):
    """Generates budget using selected provider via LiteLLM."""
    kwargs = {
        "model": model_name,
        "messages": [
            {"role": "system", "content": SYSTEM_PROMPT},
            {"role": "user", "content": text}
        ],
        "temperature": 0.3
    }
    
    # Check if OpenAI and handle response_format if so
    if "gpt-" in model_name:
        kwargs["response_format"] = {"type": "json_object"}
    
    response = litellm.completion(**kwargs)
    raw_content = response.choices[0].message.content
    return extract_json(raw_content)

def save_outputs(data):
    # Save as JSON
    with open("budget_plan.json", "w", encoding="utf-8") as f:
        json.dump(data, f, indent=2)

    # Save as human-readable TXT
    with open("budget_plan.txt", "w", encoding="utf-8") as f:
        f.write(f"BUDGET PLAN REPORT ({date.today()})\n")
        f.write("=" * 60 + "\n\n")
        
        f.write("📊 SUMMARY\n")
        f.write("-" * 15 + "\n")
        f.write(data["budget_summary"] + "\n\n")
        
        f.write("💰 ALLOCATIONS\n")
        f.write("-" * 15 + "\n")
        for a in data["allocations"]:
            if isinstance(a, dict):
                f.write(f"• {a.get('category', 'Category')}: {a.get('amount', 'N/A')} ({a.get('percentage', 'N/A')})\n")
                if a.get('notes'):
                    f.write(f"  Notes: {a['notes']}\n")
            else:
                f.write(f"• {a}\n")
        
        f.write(f"\n💵 REMAINING BALANCE: {data['remaining_balance']}\n\n")
        
        f.write("🎯 GOAL ALIGNMENT & NOTES\n")
        f.write("-" * 15 + "\n")
        for g in data["goal_alignment_notes"]:
            f.write(f"- {g}\n")
        
        f.write("\n" + "=" * 60 + "\n")
        f.write("DISCLAIMER: This budget is generated by an AI agent and is for planning purposes only. It does not constitute financial advice.\n")

def main():
    print("🚀 Starting Budget Planning Agent...")
    input_text = read_input()
    if not input_text:
        return

    print("🧠 Analyzing financial data and generating budget...")
    try:
        budget = generate_budget(input_text)
        save_outputs(budget)
        print("✅ Budget plan generated successfully!")
        print("📁 Outputs saved to budget_plan.json and budget_plan.txt")
    except Exception as e:
        print(f"❌ Error generating budget: {e}")

if __name__ == "__main__":
    main()
