import os
import json
from openai import OpenAI
from datetime import date
from dotenv import load_dotenv

# Load environment variables (e.g., from ../../.env)
load_dotenv(dotenv_path=os.path.join(os.path.dirname(__file__), "..", "..", ".env"))

# Initialize OpenAI client - it will use OPENAI_API_KEY environment variable
client = OpenAI()

SYSTEM_PROMPT = """
You are a Budget Planning Agent.

Rules:
- Create realistic, structured budgets
- Align allocations with goals
- Highlight trade-offs
- Do NOT give financial advice

Return ONLY valid JSON with this schema:

{
  "budget_summary": "Overall summary of the budget",
  "allocations": [
    {
      "category": "Category name",
      "amount": "$Amount",
      "percentage": "Percentage of total income",
      "notes": "Optional notes"
    }
  ],
  "remaining_balance": "$Remaining amount",
  "goal_alignment_notes": [
    "Note on how this aligns with the user's goals"
  ]
}
"""

def read_input(path="budget_input.txt"):
    try:
        with open(path, "r", encoding="utf-8") as f:
            return f.read()
    except FileNotFoundError:
        print(f"Error: {path} not found.")
        return None

def generate_budget(text):
    # Using gpt-4o-mini as gpt-4.1-mini is not a standard OpenAI model name
    response = client.chat.completions.create(
        model="gpt-4o-mini",
        messages=[
            {"role": "system", "content": SYSTEM_PROMPT},
            {"role": "user", "content": text}
        ],
        temperature=0.3,
        response_format={"type": "json_object"}
    )
    return json.loads(response.choices[0].message.content)

def save_outputs(data):
    # Save as JSON
    with open("budget_plan.json", "w", encoding="utf-8") as f:
        json.dump(data, f, indent=2)

    # Save as human-readable TXT
    with open("budget_plan.txt", "w", encoding="utf-8") as f:
        f.write(f"BUDGET PLAN REPORT ({date.today()})\n")
        f.write("=" * 60 + "\n\n")
        
        f.write("📊 SUMMARY\n")
        f.write("-" * 15 + "\n")
        f.write(data["budget_summary"] + "\n\n")
        
        f.write("💰 ALLOCATIONS\n")
        f.write("-" * 15 + "\n")
        for a in data["allocations"]:
            if isinstance(a, dict):
                f.write(f"• {a.get('category', 'Category')}: {a.get('amount', 'N/A')} ({a.get('percentage', 'N/A')})\n")
                if a.get('notes'):
                    f.write(f"  Notes: {a['notes']}\n")
            else:
                f.write(f"• {a}\n")
        
        f.write(f"\n💵 REMAINING BALANCE: {data['remaining_balance']}\n\n")
        
        f.write("🎯 GOAL ALIGNMENT & NOTES\n")
        f.write("-" * 15 + "\n")
        for g in data["goal_alignment_notes"]:
            f.write(f"- {g}\n")
        
        f.write("\n" + "=" * 60 + "\n")
        f.write("DISCLAIMER: This budget is generated by an AI agent and is for planning purposes only. It does not constitute financial advice.\n")

def main():
    print("🚀 Starting Budget Planning Agent...")
    input_text = read_input()
    if not input_text:
        return

    print("🧠 Analyzing financial data and generating budget...")
    try:
        budget = generate_budget(input_text)
        save_outputs(budget)
        print("✅ Budget plan generated successfully!")
        print("📁 Outputs saved to budget_plan.json and budget_plan.txt")
    except Exception as e:
        print(f"❌ Error generating budget: {e}")

if __name__ == "__main__":
    main()
